---
development:
  cloud_name: spetsnaz
  api_key: '571184654937251'
  api_secret: pXBpdlBKb_CW9SAXcOKDmFuvepA
  enhance_image_tag: true
  static_file_support: false
  secure: true
production:
  cloud_name: spetsnaz
  api_key: '571184654937251'
  api_secret: pXBpdlBKb_CW9SAXcOKDmFuvepA
  enhance_image_tag: true
  static_file_support: true
  secure: true
test:
  cloud_name: spetsnaz
  api_key: '571184654937251'
  api_secret: pXBpdlBKb_CW9SAXcOKDmFuvepA
  enhance_image_tag: true
  static_file_support: false
  secure: true